--- nnaaaz_mario2_ext.lua
--
-- This file builds the Mario2 script with extended features.
--
-- @author TFM:Nnaaaz#0000 (map, lua script)
-- @author TFM:Pshy#3752 DC:Pshy#7998 (lua script)
--
-- @require nnaaaz_mario2.lua
-- @require pshy_fcplatform.lua
-- @require pshy_speedfly.lua
